# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # name of the job
    name: build1
    
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Run a one-line script
      run: echo Hello, world!

    # Runs a set of commands using the runners shell
    - name: Run a multi-line script
      shell: bash
      env:
        REPO_SECRET: ${{ secrets.REPO_SECRET }}
        MY_SECRET: ${{ secrets.MY_SECRET }}
      run: |
        echo "$REPO_SECRET"
        echo "$MY_SECRET"
        
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: 12
        
    - run: |
        cd ./.github/actions/timelogger
        npm install
        
    # Runs a set of commands using the runners shell
    - id: timelogger
      name: Run my own GitHub Action
      uses: ./.github/actions/timelogger
      with: 
        workflow-name: ${{ github.workflow }}

    -  name: PR Comment
       uses: github-actions-up-and-running/pr-comment@v1.0.1
       with:
          # GITHUB_TOKEN secret
          repo-token: ${{ secrets.GITHUB_TOKEN }} 
          # Message to comment
          message: ${{ format('Workflow executed at {0}.', steps.timelogger.outputs.time) }}

  # This workflow contains a single job called "build-react"
  build-react:
    # name of the job
    name: build-react
    
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    
    # install node js to use npm
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: 12
    
    # package restore
    - name: yarn actions (yaml)
      uses: sergioramos/yarn-actions@v6
    
    # enforce coding standard
    - uses: hallee/eslint-action@1.0.3
      with:
        repo-token: ${{secrets.GITHUB_TOKEN}}
    
    # testing
    - run: |
        npm run test
    
    # build
    - run: |
        npm run build
